[tool.poetry]
name = "lclstream"
version = "0.3.0"
description = "Image streaming application for psana."
authors = ["Cong Wang <wangimagine@gmail.com>", "David M. Rogers <predictivestatmech@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7"
pyyaml = "^6.0.1"
msgpack = ">=1.0"
h5py = ">=3.8"
hdf5plugin = "^4.4.0"
fastapi = ">=0.103.2"
pydantic = ">=2.1"
uvicorn = ">=0.17"
numpy = ">=1.21"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
